services:
  - type: web
    name: user-auth-api
    runtime: docker
    env: python
    buildCommand: |
      pip install uv && 
      uv venv .venv && 
      . .venv/bin/activate && 
      uv pip install -e .
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1